### ISSUE TITLE
Support for ARM image

### ISSUE THREAD

**Issue by filetvignon** [marklogic/marklogic-docker#181]
Are there any plans to release ARM images of MarkLogic in the near future?

While I'm able to run the AMD64 images on Apple Silicon (Docker uses Rosetta to run the images), I often run into unexpected issues.

**Comment by jkerr5** [comment]
Support for ARM is on the roadmap for 2023 which is currently being planned.

With the release of macOS Ventura, the ability to run Rosetta inside linux containers makes a big difference. UTM now supports launching ARM VMs with Rosetta enabled and I have been running it with good success over the last month.
