### ISSUE TITLE
Upgrading existing Docker container causes endless restart loop

### ISSUE THREAD

**Issue by grtjn** [marklogic/marklogic-docker#183]
I was upgrading a pre-11 container to 11, and the logic to detect init seems to have changed. It is now looking for DOCKER_INIT. If not found, it tries to initialize, but that fails if it is already initialized, because the endpoints are already password protected.

A quick fix is to run `sudo touch /var/opt/MarkLogic/DOCKER_INIT` inside the container, either via Portainer console (be quick though), or using docker run from host command-line.

Not sure if the new start script can be improved to handle this upgrade scenario in a better way. Should be a one-time fix (for each container).

**Comment by grtjn** [comment]
Sorry, I meant docker exec: `docker exec -it jenkins-marklogic sudo touch /var/opt/MarkLogic/DOCKER_INIT`

**Comment by vitalykorolev** [comment]
Good catch! We'll address this as soon as possible.

**Comment by grtjn** [comment]
We have upgraded all our dev containers, so we are good..

**Comment by vitalykorolev** [comment]
Thanks for the update. The upgrade scenario you describe here is from Early Access (EA) to General Availability (GA) release which is not supported.

**Comment by grtjn** [comment]
No, we never used Early Access versions of MarkLogic. We just used earlier versions of MarkLogic Docker images, including marklogicdb/marklogic-server:10.0-4.2-dev-centos, and upgraded that 10.0-6.1, 10.0-7.1, 10.0-8.3 (all with similar naming), and 10.0-9.5 (the first using marklogicdb/marklogic-db:10.0-9.5-centos-1.0.0 kind of naming).

**Comment by grtjn** [comment]
I am pretty sure there will be other doing the same, and attempting to upgrade an already-initialized MarkLogic from an older container to latest.

**Comment by jkerr5** [comment]
What version/tag were you upgrading from?

**Comment by grtjn** [comment]
Most were on marklogicdb/marklogic-server:10.0-8.3-dev-centos when going to 11.0.0, except for one that I upgraded to marklogicdb/marklogic-db:10.0-9.5-centos-1.0.0 first, and then on to 11.0.0.

I am not entirely sure whether the issue occured going from 10-8 to 10-9, or from 10-9 to 11, but it did occur for at least one, as I had to apply the fix to all our dev containers.

**Comment by grtjn** [comment]
We use docker-compose to create isolated networks for each container, and mount a local subfolder to hold /var/opt/MarkLogic/ to make it survive upgrades etc..

**Comment by jkerr5** [comment]
Yeah, that would have happened for changing from the marklogicdb/marklogic-server (old development-only containers) to marklogicdb/marklogic-db (the new development or production containers). The images are different and use different startup processes. 

Since the volume you were using already had a configuration for an initialized MarkLogic, you should have set `MARKLOGIC_INIT=false`

**Comment by jkerr5** [comment]
We will update the instructions for upgrade to remove the `MARKLOGIC_INIT=true` parameter as the assumption is that MarkLogic has been initialized if you are upgrading.

**Comment by grtjn** [comment]
You don't typically change the docker-compose, just to change such a setting. Moreover, we occasionally stop the container, flush the data dir, and start the container again after which it restarts the init. I would not remove the MARKLOGIC_INIT=true flag, but rather add the DOCKER_INIT file like I described, automaticaly or manually. Could be part of some upgrade documentation.
