### ISSUE TITLE
401 when using docker run from readme example

### ISSUE THREAD

**Issue by germanbraun** [marklogic/marklogic-docker#211]
I am following this example

```
$ docker run -d -it -p 8000:8000 -p 8001:8001 -p 8002:8002 \ 
     -e MARKLOGIC_INIT=true \
     -e MARKLOGIC_ADMIN_USERNAME='admin' \
     -e MARKLOGIC_ADMIN_PASSWORD='Areally!PowerfulPassword1337' \
     marklogicdb/marklogic-db
```
but got this response:

Info: Installing admin username and password, and initialize the security database and objects.
Expected response code 202, got 401 from http://localhost:8001/admin/v1/instance-admin.

I tried sudo but did not work.
Any help?

**Comment by vitalykorolev** [comment]
I wasn't able to reproduce this issue. Could you provide more information about your environment? (OS, container runtime, etc.)

**Comment by germanbraun** [comment]
Hi Vitaly! let me know if this is enough for you:

macOS ventura 13.3.1 (MacBook Pro M1)
Docker: 20.10.23
Compose: v2.15.1
Docker desktop: 4.17.0

**Comment by jkerr5** [comment]
Do you have the rosetta 2 beta feature enabled on Docker desktop? That is required in order to run on M1.

**Comment by germanbraun** [comment]
> Do you have the rosetta 2 beta feature enabled on Docker desktop? That is required in order to run on M1.

Thanks ! I will check that

**Comment by germanbraun** [comment]
> Do you have the rosetta 2 beta feature enabled on Docker desktop? That is required in order to run on M1.

I enabled this and restarted:
**Use Virtualization framework
Uses Virtualization framework for creating and managing Docker Desktop Linux VM in macOS 12.5 and above.**

but it did not work. Is that the option you were talking about?

**Comment by jkerr5** [comment]
That is part of it but there is a Rosetta 2 option under the "Features in Development" section. This post has a good description of the steps to enable it: https://levelup.gitconnected.com/docker-on-apple-silicon-mac-how-to-run-x86-containers-with-rosetta-2-4a679913a0d5

**Comment by germanbraun** [comment]
> That is part of it but there is a Rosetta 2 option under the "Features in Development" section. This post has a good description of the steps to enable it: https://levelup.gitconnected.com/docker-on-apple-silicon-mac-how-to-run-x86-containers-with-rosetta-2-4a679913a0d5

Yeah, i see. Thanks!

**Comment by vitalykorolev** [comment]
@germanbraun was your issue resolved?

**Comment by germanbraun** [comment]
> @germanbraun was your issue resolved?

Hi @vitalykorolev not yet. I followed the steps in the post referenced by @jkerr5 but I cannot see the "rosetta2" option in my Docker Desktop under "Features in Development".
Have you tried this on any M1? any other pointer?

Thanks a lot!

**Comment by germanbraun** [comment]
> > @germanbraun was your issue resolved?
> 
> Hi @vitalykorolev not yet. I followed the steps in the post referenced by @jkerr5 but I cannot see the "rosetta2" option in my Docker Desktop under "Features in Development". Have you tried this on any M1? any other pointer?
> 
> Thanks a lot!

I am now updating my mac to see if this would solve the issue

**Comment by germanbraun** [comment]
After updating my macOS version to the latest, the option to enable rosetta2 on Docker Desktop appeared and finally it worked!

That was my test:

`docker run -d -it --privileged -p 8000:8000 -p 8001:8001 -p 8002:8002 -e MARKLOGIC_INIT=true -e MARKLOGIC_ADMIN_USERNAME='admin' -e MARKLOGIC_ADMIN_PASSWORD='Areally!PowerfulPassword1337' marklogicdb/marklogic-db`

Thanks for your help!

**Comment by vitalykorolev** [comment]
I'm glad you were able to figure this out!

**Comment by germanbraun** [comment]
Hi again :)
I am getting the very same issue but now trying to run it by using docker compose. This is my .yaml file

`version: '3.6'
services:
  bootstrap:
    image: marklogicdb/marklogic-db
    container_name: bootstrap
    hostname: bootstrap
    restart: unless-stopped
    dns_search: ""
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_WALLET_PASSWORD_FILE=admin
      - REALM=public
      - TZ=Europe/Germany
    volumes:
      - marklogic_data:/var/opt/MarkLogic
    ports:
      - 8000-8002:8000-8002
    networks:
      - external_net

volumes:
  marklogic_data:

networks:
  external_net: {}`
