### ISSUE TITLE
401 by now using docker-compose (related to #211)

### ISSUE THREAD

**Issue by germanbraun** [marklogic/marklogic-docker#212]
Hi again :)
I am getting the very same issue than in my previous issue (https://github.com/marklogic/marklogic-docker/issues/211) but now trying to run it by using docker compose. This is my .yaml file

`version: '3.6'
services:
  bootstrap:
    image: marklogicdb/marklogic-db
    container_name: bootstrap
    hostname: bootstrap
    restart: unless-stopped
    dns_search: ""
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_WALLET_PASSWORD=admin
      - REALM=public
      - TZ=Europe/Germany
    volumes:
      - marklogic_data:/var/opt/MarkLogic
    ports:
      - 8000-8002:8000-8002
    networks:
      - external_net

volumes:
  marklogic_data:

networks:
  external_net: {}`

_Originally posted by @germanbraun in https://github.com/marklogic/marklogic-docker/issues/211#issuecomment-1536613319_

**Comment by germanbraun** [comment]
Info: Installing admin username and password, and initialize the security database and objects.
Expected response code 202, got 401 from http://localhost:8001/admin/v1/instance-admin.

**Comment by germanbraun** [comment]
Regarding versions, I am using docker compose v2 but not docker-compose v1.

**Comment by vitalykorolev** [comment]
One common issue with compose is reuse of volumes. If you deploy the same yaml more than once, please be sure to delete volumes that remain. In your example it's "marklogic_data".

**Comment by germanbraun** [comment]
> One common issue with compose is reuse of volumes. If you deploy the same yaml more than once, please be sure to delete volumes that remain. In your example it's "marklogic_data".

Thanks Vitaly. I removed all the volumes but the issue is still there.
What about versions? I mean, is it ok run the above yml file using compose v2 instead of v1? I just thinking ...

**Comment by vitalykorolev** [comment]
I think we have both v1 and v2, but I have yet to reproduce your issue on M1 mac with Docker desktop and compose.

**Comment by atb-brown** [comment]
I think I'm having the same issue, if not a very similar one.

MacOS Venutra 13.3.1 (a)
Chip: Apple M2 Max
Docker v4.19.0
marklogicdb/marklogic-db:10.0-9.5-centos-1.0.2

Where my issue seems to diverge is that when the container tries to do that admin authentication, it uses `marklogic` for the hostname instead of `localhost`. I'm not sure if that's a red-herring or not, but we're using `marklogic` as the hostname in our `docker-compose.yml`.

```
2023-05-25 15:14:46 workbench  | 2023-05-25 20:14:46.987 Info: Installing admin username and password, and initialize the security database and objects.
2023-05-25 15:16:07 workbench  | 2023-05-25 20:16:07.633 Error: Expected response code 202, got 401 from http://marklogic:8001/admin/v1/instance-admin.
```

I'm supposing this has something to do with the Apple Silicon chips because no Windows users on my team are encountering this issue and neither is the other Mac developer that has an intel chip.

**Comment by atb-brown** [comment]
Out of curiosity, I also tried the `10.0-3-dev-ubi` tag and I have same issue I've described above.

**Comment by atb-brown** [comment]
I switched to Rancher Desktop and it appears that this issue does not occur with Rancher; so I think it's safe to say that there's some virtualization messiness happening with Docker on Apple Silicon chips.

**Comment by anthonyhashemi** [comment]
I am also getting this issue with docker-compose but not with the equivalent docker run.

I am on an intel mac, so I don't believe it is apple silicon exclusive.

**Comment by sumanthravipati** [comment]
We tested it on intel mac using docker-compose v2 and everything works as expected and couldn't reproduce the issue.

On Apple Silicon Chips, make sure that you have Rosetta 2 emulation and also allocate enough memory (4GB-8GB) to spin up MarkLogic containers. 

If both are taken care and still you see the same issue, look at the Errorlog.txt file on why it is giving 401 error and provide us with more information for debugging purposes.
