### ISSUE TITLE
MARKLOGIC_VERSION 10-internal on image marklogicdb/marklogic-db:10.0-10.2-centos-1.0.2

### ISSUE THREAD

**Issue by ilanRosenbaum** [marklogic/marklogic-docker#220]
I am building a MarkLogic docker container using this command in my Dockerfile `FROM marklogicdb/marklogic-db:10.0-10.2-centos-1.0.2` when I look through the layers of the Docker image in my Docker Desktop I see `ARG ML_VERSION=10-internal`. I am not sure if this bug is causing any actual issues as from the digging I've done ML_VERSION is only used for lables. Thes startup script and everything else I can find uses MARKLOGIC_VERSION not ML_VERSION. The ML_VERSION arg is hard coded into the marklogic-server-centos:base file before getting variables from the env. It seems to me this issue could easily be fixed by moving the set env variable code above `# define docker labels` and use MARKLOGIC_VERSION instead of ML_VERSION.

**Comment by sumanthravipati** [comment]
This is expected behaviour as we use a base image to build the actual image when the version is not available.
